name: Auto-Commit Codespace
on:
  schedule:
    - cron: '0 * * * *'  # Läuft jede Stunde
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Repo clonen
        uses: actions/checkout@v3

      - name: Änderungen speichern
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatische Sicherung" || echo "Keine Änderungen zum Committen"
          git push origin main || echo "Nichts zu pushen"
